In [ ]:
'''

This code is designed to filter data from a .csv file generated by ABET software based upon user input

Generating a data table and filtering is the first step to aligning behavioral epochs with calcium imaging data

'''

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("74 12042019.csv")

In [6]:
data.head(1)

,Evnt_Time,Evnt_ID,Evnt_Name,Item_Name,Alias_Name,Group_ID,Num_Args,Arg1_Name,Arg1_Value,Arg2_Name,Arg2_Value,Arg3_Name,Arg3_Value,Arg4_Name,Arg4_Value,Arg5_Name,Arg5_Value
0,0.0,28,Input Definition,(SYSTEM),NaN,0,5,Tray #1,0.0,BIRBeam #1,1.0,FIRBeam #1,2.0,RightFIRBeam #1,3.0,FeederFault #1,4.0

In [6]:
# magic for Jupyter
%matplotlib inline

#import the read_block function from the tdt package
#also import other python packages we care about
import numpy as np
from sklearn.metrics import auc
import matplotlib.pyplot as plt  # standard Python plotting library
import scipy.stats as stats

from tdt import read_block, epoc_filter, download_demo_data

#%% Importing the Data
BLOCKPATH = 'E:/MATLAB/TDTbin2mat/Photometry/66 & 67/66_and_67-191028-132849'
data = read_block(BLOCKPATH)

read from t=0s to t=2244.64s

In [10]:
data.streams.d0sP[]

TypeError: 'StructType' object is not callable