In [ ]:
'''

This code is designed to filter data from a .csv file generated by ABET software based upon user input

Generating a data table and filtering is the first step to aligning behavioral epochs with calcium imaging data

'''

In [7]:
import pandas as pd

In [22]:
data = pd.read_csv("74 12042019.csv")

In [30]:
large_rew = data.Arg1_Value == 0.3

In [32]:
forced_trial = data.Group_ID == 9

In [33]:
free_trial = data.Group_ID == 12

In [35]:
filtered  = data[large_rew & free_trial]

Evnt_Time                                                 69521
Evnt_ID                                                     147
Evnt_Name     Pulse Output EventPulse Output EventPulse Outp...
Item_Name     Feeder #2Feeder #2Feeder #2Feeder #2Feeder #2F...
Alias_Name                                                    0
Group_ID                                                    252
Num_Args                                                     21
Arg1_Name     DurationDurationDurationDurationDurationDurati...
Arg1_Value                                                  6.3
Arg2_Name                                                     0
Arg2_Value                                                    0
Arg3_Name                                                     0
Arg3_Value                                                    0
Arg4_Name                                                     0
Arg4_Value                                                    0
Arg5_Name                                                     0
Arg5_Value                                                    0
dtype: object

In [20]:
data.Arg1_Value

0       0.3
1       0.3
2       0.3
3       0.3
4       0.3
5       0.3
6       0.3
7       0.3
8       0.3
9       0.3
10      0.3
11      0.3
12      0.3
13      0.3
14      0.3
15      0.3
16      0.3
17      0.3
18      0.3
19      0.3
20      0.3
21      0.3
22      0.3
23      0.3
24      0.3
25      0.3
26      0.3
27      0.3
28      0.3
29      0.3
       ...
9635    0.3
9636    0.3
9637    0.3
9638    0.3
9639    0.3
9640    0.3
9641    0.3
9642    0.3
9643    0.3
9644    0.3
9645    0.3
9646    0.3
9647    0.3
9648    0.3
9649    0.3
9650    0.3
9651    0.3
9652    0.3
9653    0.3
9654    0.3
9655    0.3
9656    0.3
9657    0.3
9658    0.3
9659    0.3
9660    0.3
9661    0.3
9662    0.3
9663    0.3
9664    0.3
Name: Arg1_Value, Length: 9665, dtype: float64

In [15]:
large_rew_filter = data.

,Evnt_Time,Evnt_ID,Evnt_Name,Item_Name,Alias_Name,Group_ID,Num_Args,Arg1_Name,Arg1_Value,Arg2_Name,Arg2_Value,Arg3_Name,Arg3_Value,Arg4_Name,Arg4_Value,Arg5_Name,Arg5_Value
0,0.0,28,Input Definition,(SYSTEM),NaN,0,5,Tray #1,0.0,BIRBeam #1,1.0,FIRBeam #1,2.0,RightFIRBeam #1,3.0,FeederFault #1,4.0
1,0.0,28,Input Definition,(SYSTEM),NaN,0,1,FeederReport #1,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,27,Output Definition,(SYSTEM),NaN,0,5,HouseLight #1,0.0,TrayLight #1,1.0,Feeder #1,2.0,Sound_On #1,3.0,White_Noise_Off #1,4.0
3,0.0,27,Output Definition,(SYSTEM),NaN,0,5,Sound #1,5.0,Sound #2,6.0,Sound #3,7.0,Shocker #1,8.0,Laser #1,9.0
4,0.0,27,Output Definition,(SYSTEM),NaN,0,5,Feeder #2,14.0,PlexonBit #1,21.0,PlexonBit #2,22.0,PlexonBit #3,23.0,PlexonBit #4,24.0
5,0.0,27,Output Definition,(SYSTEM),NaN,0,5,PlexonBit #5,25.0,PlexonBit #6,26.0,PlexonBit #7,27.0,PlexonBit #8,28.0,Strobe #1,29.0
6,0.0,16,Variable Event,_Schedule_Timer,NaN,0,1,Value,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0.0,16,Variable Event,_Trial_Counter,NaN,0,1,Value,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,0.0,16,Variable Event,_Trial_Timer,NaN,0,1,Value,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,0.0,16,Variable Event,Big_Grid_Position,NaN,0,1,Value,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
count()

In [6]:
# magic for Jupyter
%matplotlib inline

#import the read_block function from the tdt package
#also import other python packages we care about
import numpy as np
from sklearn.metrics import auc
import matplotlib.pyplot as plt  # standard Python plotting library
import scipy.stats as stats

from tdt import read_block, epoc_filter, download_demo_data

#%% Importing the Data
BLOCKPATH = 'E:/MATLAB/TDTbin2mat/Photometry/66 & 67/66_and_67-191028-132849'
data = read_block(BLOCKPATH)

read from t=0s to t=2244.64s

In [10]:
data.streams.d0sP[]

TypeError: 'StructType' object is not callable